markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables", "strikethrough"]
permalink: /:year/:month/:day/:title 
title: Mind Geeker
url: villa0840.github.io
githubEditBaseURL: 
subscribe: 
exclude: [ README.md, newpost.rb ]
domain: 
author: Villa
email: hj25133778@gmail.com
googleAnalyticsID: 
disqusShortname: 
timezone: Asia/Shanghai
